#!/bin/bash
mkdir ~/.ssh
cd ~/.ssh && ssh-keygen -t rsa -b 4096 -C "email@example.com"
git clone <username>@<hostname>:<repository>.git
#git clone --bare myproject  ssh://user@server:/GitRepos/myproject.git
#https://devconnected.com/how-to-clone-a-git-repository/
