#!/bin/bash
cd ..
sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
sudo yum -y install terraform
cp $(which terraform) ~/bin
cd terraform-vpc/module-vpc
terraform init
terraform plan
terraform apply -auto-approve
